import React from "react";
import Head from "next/head";
import { Montserrat } from "@next/font/google";
import Link from "next/link";

const montserrat = Montserrat({ subsets: ["latin"] });

export interface LayoutProps {
  children: React.ReactNode;
  title: string;
  description: string;
}

export const Layout: React.FunctionComponent<LayoutProps> = ({
  children,
  title,
}) => {
  return (
    <>
      <Head>
        <title>{title ? `${title} | weather-app` : "weather-app"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${montserrat.className} mx-auto max-w-[90%] w-[800px] pb-16`}
      >
        <nav className="pt-4">
          <Link href="/" className="text-2xl font-bold">
            Weather App
          </Link>
        </nav>
        <main>{children}</main>
      </div>
    </>
  );
};
